version: '3.9'
services:
  java_app:
    container_name: java_app
    image: pee-java-app:1.0.0
    build: back/libreria2/
    ports:
      - 8080:8080
    environment:
      - DATABASE_URL=jdbc:postgresql://javadb:5432/libreria
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=123matias456
    depends_on:
    -  javadb

  javadb:
    container_name: javadb
    image: postgres
    environment:
    - POSTGRES_DB=libreria
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=123matias456
    volumes:
      - javadb_data:/var/lib/postgresql/data

  vue_app:
    build: front/libreria2/
    ports:
      - 5173:5173
    depends_on:
      - javadb
      - java_app
      
volumes:
  javadb_data: